#!/bin/bash
# Script to display all active IPv4 IPs on the machine

# Extract and display all active IPv4 IP addresses
ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | grep -v "127.0.0.1" | cut -d ' ' -f 2 | cut -d ':' -f 2
